# Generated by Django 3.0.4 on 2020-04-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=100)),
                ('main_ingredient', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('in_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_list.Book')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
