# Generated by Django 3.0.4 on 2020-04-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='page',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
