# Generated by Django 3.0.4 on 2020-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0003_foodgroup_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
