# Generated by Django 3.0.4 on 2020-05-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0005_auto_20200503_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='the_list.FoodGroup'),
        ),
    ]
