# Generated by Django 3.0.4 on 2020-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0008_auto_20200525_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
