# Generated by Django 3.0.4 on 2020-05-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_list.Category'),
        ),
    ]
