# Generated by Django 3.0.4 on 2020-05-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0011_auto_20200531_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateField(auto_now_add=True)),
                ('tried_it', models.BooleanField(default=False)),
                ('comment_made', models.CharField(blank=True, max_length=150)),
                ('about_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_list.Recipe')),
            ],
            options={
                'ordering': ['-made_on'],
            },
        ),
    ]
