# Generated by Django 3.0.7 on 2020-11-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0014_auto_20200601_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_file',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]
