# Generated by Django 3.0.7 on 2020-11-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0015_recipe_recipe_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
